version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: shareIt_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
    volumes:
      - ./shareit-server/src/main/resources:/docker-entrypoint-initdb.d

  server:
    build: shareIt-server
    container_name: shareIt_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  gateway:
    build: gateway
    container_name: shareIt_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
