CREATE TABLE IF NOT EXISTS app_user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    is_available BOOLEAN,
    owner_id     BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    start_date date,
    end_date   date,
    item_id    BIGINT,
    status     INTEGER,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES app_user (id);